### ISSUE TITLE
Exeption-Meldungen nach Update unter TYPO3 4.7.20

### ISSUE THREAD

**Issue by bastians** [digedag/t3sponsors#3]
Ich habe den aktuellesten Stand des Masters von hier nun in meine TYPO3 v4.7.20 einspielen wollen, damit ich für das anstehende Update gewappnet bin. Ich erhalte nun aber folgende Expetions:

```
This is an automatic email from TYPO3. Don't answer!
UNCAUGHT EXCEPTION FOR VIEW: tx_t3sponsors_actions_SponsorList
Message:
Class path not found: [...]typo3conf/ext/rn_base/maps/ILocation/class.tx_rnbase_maps_ILocation.php

Stacktrace:

exception 'Exception' with message 'Class path not found: [...]typo3conf/ext/rn_base/maps/ILocation/class.tx_rnbase_maps_ILocation.php' in [...]typo3conf/ext/rn_base/class.tx_rnbase.php:306
Stack trace:
#0 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(327): tx_rnbase::getClassInfo('tx_rnbase_maps_...', '')
#1 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(183): tx_rnbase::_findT3('tx_rnbase_maps_...', '', 'class.', '.php')
#2 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(49): tx_rnbase::loadT3('tx_rnbase_maps_...')
#3 [...]typo3conf/ext/t3sponsors/models/class.tx_t3sponsors_models_Sponsor.php(29): tx_rnbase::load('tx_rnbase_maps_...')
#4 [...]t3lib/class.t3lib_div.php(5158): require_once('/is/htdocs/wp10...')
#5 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(186): t3lib_div::requireOnce('/is/htdocs/wp10...')
#6 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(49): tx_rnbase::loadT3('tx_t3sponsors_m...')
#7 [...]typo3conf/ext/rn_base/class.tx_rnbase.php(85): tx_rnbase::load('tx_t3sponsors_m...')
#8 [...]typo3conf/ext/rn_base/util/class.tx_rnbase_util_DB.php(179): tx_rnbase::makeInstance('tx_t3sponsors_m...', Array)
#9 [...]typo3conf/ext/rn_base/util/class.tx_rnbase_util_SearchBase.php(305): tx_rnbase_util_DB::doSelect('DISTINCT SPONSO...', Array, Array, 0)
#10 [...]typo3conf/ext/t3sponsors/sv1/class.tx_t3sponsors_sv1_Sponsor.php(46): tx_rnbase_util_SearchBase->search(Array, Array)
#11 [...]typo3conf/ext/t3sponsors/actions/class.tx_t3sponsors_actions_SponsorList.php(58): tx_t3sponsors_sv1_Sponsor->search(Array, Array)
#12 [...]typo3conf/ext/rn_base/action/class.tx_rnbase_action_BaseIOC.php(83): tx_t3sponsors_actions_SponsorList->handleRequest(Object(tx_rnbase_parameters), Object(tx_rnbase_configurations), Object(ArrayObject))
#13 [...]typo3conf/ext/rn_base/class.tx_rnbase_controller.php(252): tx_rnbase_action_BaseIOC->execute(Object(tx_rnbase_parameters), Object(tx_rnbase_configurations))
#14 [...]typo3conf/ext/rn_base/class.tx_rnbase_controller.php(227): tx_rnbase_controller->doAction('tx_t3sponsors_a...', Object(tx_rnbase_parameters), Object(tx_rnbase_configurations))
#15 [internal function]: tx_rnbase_controller->main('', Array)
#16 [...]typo3/sysext/cms/tslib/class.tslib_content.php(6585): call_user_func_array(Array, Array)
#17 [...]typo3/sysext/cms/tslib/content/class.tslib_content_user.php(55): tslib_cObj->callUserFunction('tx_rnbase_contr...', Array, '')
#18 [...]typo3/sysext/cms/tslib/class.tslib_content.php(780): tslib_content_User->render(Array)
#19 [...]typo3/sysext/cms/tslib/class.tslib_fe.php(3307): tslib_cObj->USER(Array)
#20 [...]typo3/sysext/cms/tslib/class.tslib_fe.php(3243): tslib_fe->INTincScript_process(Array)
#21 [...]typo3/sysext/cms/tslib/index_ts.php(367): tslib_fe->INTincScript()
#22 [...]index.php(76): require('/is/htdocs/wp10...')
#23 {main}
SITE_URL
http://www.fvloechgau.de/

_GET
array ( 'cfc_league_fe' => array ( 'saison' => '6', ), )

_COOKIE
array ( '__utma' => '107315029.1442682534.1467882608.1468401297.1469456628.3', '__utmz' => '107315029.1468401297.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not provided)', 'fe_typo_user' => '8d4f0cf2fd162eb56df47dcbedf1faa2', '__utmb' => '107315029.8.10.1469456628', '__utmc' => '107315029', '__utmt' => '1', )

_SERVER
array ( 'REDIRECT_HOME' => '/is/htdocs/wp10621052_KBL8Q09Y2Z/', 'REDIRECT_USER' => 'wp10621052', 'REDIRECT_STATUS' => '200', 'HOME' => '/is/htdocs/wp10621052_KBL8Q09Y2Z/', 'USER' => 'wp10621052', 'HTTP_HOST' => 'www.fvloechgau.de', 'HTTP_X_REAL_IP' => '194.116.206.16', 'HTTP_X_FORWARDED_FOR' => '194.116.206.16', 'HTTP_CONNECTION' => 'close', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0', 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'HTTP_ACCEPT_LANGUAGE' => 'de,en-US;q=0.7,en;q=0.3', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate', 'HTTP_REFERER' => 'https://www.google.de', 'HTTP_COOKIE' => '__utma=107315029.1442682534.1467882608.1468401297.1469456628.3; __utmz=107315029.1468401297.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); fe_typo_user=8d4f0cf2fd162eb56df47dcbedf1faa2; __utmb=107315029.8.10.1469456628; __utmc=107315029; __utmt=1', 'PATH' => '/bin:/usr/bin:/usr/ucb:/usr/bsd:/usr/local/bin', 'SERVER_SIGNATURE' => '', 'SERVER_SOFTWARE' => 'Apache', 'SERVER_NAME' => 'www.fvloechgau.de', 'SERVER_ADDR' => '127.0.0.56', 'SERVER_PORT' => '80', 'REMOTE_ADDR' => '194.116.206.16', 'DOCUMENT_ROOT' => '[...]', 'SERVER_ADMIN' => 'info@fvloechgau.de', 'SCRIPT_FILENAME' => '[...]index.php', 'REMOTE_PORT' => '50293', 'REDIRECT_QUERY_STRING' => 'cfc_league_fe%5Bsaison%5D=6', 'REDIRECT_URL' => '/junioren/a1/kader.html', 'GATEWAY_INTERFACE' => 'CGI/1.1', 'SERVER_PROTOCOL' => 'HTTP/1.0', 'REQUEST_METHOD' => 'GET', 'QUERY_STRING' => 'cfc_league_fe%5Bsaison%5D=6', 'REQUEST_URI' => '/junioren/a1/kader.html?cfc_league_fe%5Bsaison%5D=6', 'SCRIPT_NAME' => '/index.php', 'PHP_SELF' => '/index.php', 'REQUEST_TIME_FLOAT' => 1469456858.2590000629425048828125, 'REQUEST_TIME' => 1469456858, 'argv' => array ( 0 => 'cfc_league_fe%5Bsaison%5D=6', ), 'argc' => 1, )

BE_USER:

FE_USER:
```

Dieser Pfad existiert in der Tat nicht: typo3conf/ext/rn_base/maps/ILocation/class.tx_rnbase_maps_ILocation.php

Die rn_base-Version, die ich einsetze, ist die 0.15.0, da ein Update meine Seite komplett lahm legt.

**Comment by digedag** [comment]
Dann wird es das Interface in der alten Version noch nicht gegeben haben.
Den Upgrade solltest du immer erst in einer Testumgebung einmal durchspielen. Bei rn_base sind in einem der letzten Tags einmal Änderungen reingelaufen, die tatsächlich zu PHP-Fehlern führen können. Die wichtigste Änderung wurde aber wieder entfernt, ist im aktuellen Head nicht mehr drin.
Du kannst aber die Version 1.0.15 nutzen, da sind diese Anpassungen komplett noch nicht drin.

`git checkout v1.0.15`

Ansonsten läuft der master von rn_base aber grundsätzlich auch noch in TYPO3 4.5. Einen Support für nicht LTS-Versionen gibt es aber nicht. Deshalb kann ich zur 4.7 nicht sagen.
Wichtig ist noch die PHP-Version. Du benötigst mindestens 5.3.9.

**Comment by bastians** [comment]
Die v1.0.15 legt schon wieder meine komplette Seite lahm. Ich habe nun die v1.0.1 von t3sponsors wieder eingespielt, nun läuft alles wieder. Ich lasse das unter 4.7 nun so und update dann erst im Zuge des Upgrades zu 6.2. Da werden bei meinen Tests aktuell zwar noch keine Bilder angezeigt, aber ich vermute das hängt mit der noch ausstehenden Migration von DAM zu FAL zusammen, kann das sein?

**Comment by digedag** [comment]
Was genau ist denn die Fehlermeldung, wenn deine Seite komplett lahm gelegt ist? Es muss doch einen PHP-Error geben?
Hast du nach dem Update den Cache geleert? Kann sein, daß dies im Backend nicht möglich ist. Dann musst du manuell die Temp-Dateien im Verzeichnis typo3conf löschen.
Es ist aber tatsächlich so, daß in rn_base nur gegen LTS-Versionen entwickelt wird. Alles andere wird viel zu aufwendig...
Deine Frage zur DAM-FAL-Migration verstehe ich nicht. In der 4.7 gibt es doch noch gar kein FAL...
